import smtplib
import logging
import json
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from app.core.config import settings
from typing import Optional


logger = logging.getLogger("email_service")


def send_maintenance_notification_email(
    email: str, payload: dict, retry_count: int = 0
) -> bool:
    """
    Send real-time maintenance notification email for machine error events.

    Args:
        email: Recipient email (maintenance responsible user)
        payload: Notification payload sent to UI websocket clients
        retry_count: Current retry attempt

    Returns:
        True if email sent successfully, False otherwise
    """
    max_retries = 3

    if not settings.SMTP_ENABLED:
        logger.warning(f"Email service is disabled. Skipping maintenance alert email for {email}")
        return True

    machine_ref = payload.get("machine_reference", "N/A")
    state = payload.get("state", "N/A")
    message = payload.get("message", "Alerte maintenance")
    payload_json = json.dumps(payload, ensure_ascii=False, indent=2)

    try:
        html_content = f"""
        <html>
            <head>
                <style>
                    body {{ font-family: Arial, sans-serif; background-color: #f4f4f4; }}
                    .container {{ max-width: 640px; margin: 0 auto; background-color: white; padding: 20px; border-radius: 8px; }}
                    .header {{ background: #b91c1c; color: white; padding: 16px; border-radius: 8px 8px 0 0; }}
                    .content {{ padding: 20px; color: #111827; }}
                    .badge {{ display: inline-block; padding: 6px 10px; border-radius: 999px; background: #fee2e2; color: #991b1b; font-weight: bold; }}
                    .payload {{ white-space: pre-wrap; background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 6px; padding: 12px; font-family: monospace; font-size: 12px; }}
                    .footer {{ margin-top: 20px; color: #6b7280; font-size: 12px; }}
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h2 style="margin:0;">Alerte maintenance en temps reel</h2>
                    </div>
                    <div class="content">
                        <p><strong>Machine:</strong> {machine_ref}</p>
                        <p><strong>Etat:</strong> <span class="badge">{state}</span></p>
                        <p><strong>Message:</strong> {message}</p>
                        <p><strong>Payload websocket (identique):</strong></p>
                        <div class="payload">{payload_json}</div>
                        <div class="footer">
                            Cet email a ete genere automatiquement par MES.
                        </div>
                    </div>
                </div>
            </body>
        </html>
        """

        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"[MES] Alerte maintenance - {machine_ref} en {state}"
        msg["From"] = settings.SMTP_FROM
        msg["To"] = email
        msg.attach(MIMEText(html_content, "html"))

        with smtplib.SMTP(settings.SMTP_SERVER, settings.SMTP_PORT) as server:
            server.starttls()
            server.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
            server.send_message(msg)

        logger.info(f"Maintenance alert email sent successfully to {email}")
        return True
    except smtplib.SMTPAuthenticationError as e:
        logger.error(f"SMTP authentication failed for maintenance alert email: {e}")
        if retry_count < max_retries:
            logger.info(f"Retrying maintenance alert email... (attempt {retry_count + 1}/{max_retries})")
            return send_maintenance_notification_email(email, payload, retry_count + 1)
        return False
    except smtplib.SMTPException as e:
        logger.error(f"SMTP error sending maintenance alert email to {email}: {e}")
        if retry_count < max_retries:
            logger.info(f"Retrying maintenance alert email... (attempt {retry_count + 1}/{max_retries})")
            return send_maintenance_notification_email(email, payload, retry_count + 1)
        return False
    except Exception as e:
        logger.error(f"Unexpected error sending maintenance alert email to {email}: {e}")
        if retry_count < max_retries:
            logger.info(f"Retrying maintenance alert email... (attempt {retry_count + 1}/{max_retries})")
            return send_maintenance_notification_email(email, payload, retry_count + 1)
        return False


def send_welcome_email(email: str, temporary_password: str, nom: str, prenom: str, retry_count: int = 0) -> bool:
    """
    Send welcome email with temporary password to new user.
    
    Args:
        email: User's email
        temporary_password: Temporary password generated by system
        nom: User's last name
        prenom: User's first name
        retry_count: Current retry attempt
    
    Returns:
        True if email sent successfully, False otherwise
    """
    max_retries = 3
    
    if not settings.SMTP_ENABLED:
        logger.warning(f"Email service is disabled. Skipping email for {email}")
        return True
    
    try:
        # Create HTML email content
        html_content = f"""
        <html>
            <head>
                <style>
                    body {{ font-family: Arial, sans-serif; background-color: #f4f4f4; }}
                    .container {{ max-width: 600px; margin: 0 auto; background-color: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
                    .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 8px 8px 0 0; text-align: center; }}
                    .header h1 {{ margin: 0; font-size: 28px; }}
                    .content {{ padding: 30px 20px; }}
                    .welcome-text {{ font-size: 16px; color: #333; margin-bottom: 20px; }}
                    .credentials {{ background-color: #f9f9f9; padding: 15px; border-left: 4px solid #667eea; margin: 20px 0; border-radius: 4px; }}
                    .credentials p {{ margin: 10px 0; font-size: 14px; }}
                    .password {{ background-color: #fff3cd; padding: 10px; border-radius: 4px; font-family: monospace; font-weight: bold; word-break: break-all; }}
                    .action-button {{ display: inline-block; background-color: #667eea; color: white; padding: 12px 30px; text-decoration: none; border-radius: 4px; margin-top: 20px; font-weight: bold; }}
                    .footer {{ text-align: center; color: #666; font-size: 12px; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; }}
                    .warning {{ background-color: #fff3cd; padding: 15px; border-radius: 4px; margin: 20px 0; color: #856404; }}
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>🏭 MES System</h1>
                        <p>Système de Gestion de Production</p>
                    </div>
                    
                    <div class="content">
                        <div class="welcome-text">
                            <p>Bonjour <strong>{prenom} {nom}</strong>,</p>
                            <p>Bienvenue dans le MES System! Un compte a été créé pour vous par un administrateur.</p>
                        </div>
                        
                        <div class="credentials">
                            <p><strong>Email:</strong> {email}</p>
                            <p><strong>Mot de passe temporaire:</strong></p>
                            <div class="password">{temporary_password}</div>
                        </div>
                        
                        <div class="warning">
                            <strong>⚠️ Important:</strong> Ce mot de passe est temporaire. Vous devrez le changer lors de votre première connexion.
                        </div>
                        
                        <p>Pour accéder à la plateforme, cliquez sur le bouton ci-dessous:</p>
                        <a href="{settings.FRONTEND_URL}/login" class="action-button">Se connecter</a>
                        
                        <p style="margin-top: 30px; font-size: 14px; color: #666;">
                            Si vous avez des questions, veuillez contacter l'équipe d'administration.
                        </p>
                    </div>
                    
                    <div class="footer">
                        <p>© 2026 MES System. Tous droits réservés.</p>
                        <p>Cet email a été généré automatiquement. Veuillez ne pas y répondre.</p>
                    </div>
                </div>
            </body>
        </html>
        """
        
        # Create message
        msg = MIMEMultipart('alternative')
        msg['Subject'] = "Bienvenue au MES System - Informations de Connexion"
        msg['From'] = settings.SMTP_FROM
        msg['To'] = email
        
        # Attach HTML content
        msg.attach(MIMEText(html_content, 'html'))
        
        # Connect to SMTP server and send
        with smtplib.SMTP(settings.SMTP_SERVER, settings.SMTP_PORT) as server:
            server.starttls()
            server.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
            server.send_message(msg)
        
        logger.info(f"Welcome email sent successfully to {email}")
        return True
        
    except smtplib.SMTPAuthenticationError as e:
        logger.error(f"SMTP authentication failed: {e}")
        if retry_count < max_retries:
            logger.info(f"Retrying... (attempt {retry_count + 1}/{max_retries})")
            return send_welcome_email(email, temporary_password, nom, prenom, retry_count + 1)
        return False


def send_password_reset_email(email: str, temporary_password: str, nom: str, prenom: str, retry_count: int = 0) -> bool:
    """
    Send password reset email with a new temporary password.

    Args:
        email: User's email
        temporary_password: Newly generated temporary password
        nom: User's last name
        prenom: User's first name
        retry_count: Current retry attempt

    Returns:
        True if email sent successfully, False otherwise
    """
    max_retries = 3

    if not settings.SMTP_ENABLED:
        logger.warning(f"Email service is disabled. Skipping password reset email for {email}")
        return True

    try:
        html_content = f"""
        <html>
            <head>
                <style>
                    body {{ font-family: Arial, sans-serif; background-color: #f4f4f4; }}
                    .container {{ max-width: 600px; margin: 0 auto; background-color: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
                    .header {{ background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%); color: white; padding: 20px; border-radius: 8px 8px 0 0; text-align: center; }}
                    .content {{ padding: 30px 20px; }}
                    .credentials {{ background-color: #f9f9f9; padding: 15px; border-left: 4px solid #1e293b; margin: 20px 0; border-radius: 4px; }}
                    .password {{ background-color: #fff3cd; padding: 10px; border-radius: 4px; font-family: monospace; font-weight: bold; word-break: break-all; }}
                    .warning {{ background-color: #fee2e2; padding: 15px; border-radius: 4px; margin: 20px 0; color: #991b1b; }}
                    .action-button {{ display: inline-block; background-color: #0f172a; color: white; padding: 12px 30px; text-decoration: none; border-radius: 4px; margin-top: 20px; font-weight: bold; }}
                    .footer {{ text-align: center; color: #666; font-size: 12px; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; }}
                </style>
            </head>
            <body>
                <div class="container">
                    <div class="header">
                        <h1>MES System</h1>
                        <p>Password Reset Notification</p>
                    </div>
                    <div class="content">
                        <p>Bonjour <strong>{prenom} {nom}</strong>,</p>
                        <p>Votre mot de passe a ete reinitialise par un administrateur.</p>

                        <div class="credentials">
                            <p><strong>Email:</strong> {email}</p>
                            <p><strong>Nouveau mot de passe temporaire:</strong></p>
                            <div class="password">{temporary_password}</div>
                        </div>

                        <div class="warning">
                            <strong>Important:</strong> Vous devez changer ce mot de passe lors de votre prochaine connexion.
                        </div>

                        <a href="{settings.FRONTEND_URL}/login" class="action-button">Se connecter</a>
                    </div>
                    <div class="footer">
                        <p>© 2026 MES System. Tous droits reserves.</p>
                    </div>
                </div>
            </body>
        </html>
        """

        msg = MIMEMultipart('alternative')
        msg['Subject'] = "MES System - Reinitialisation de mot de passe"
        msg['From'] = settings.SMTP_FROM
        msg['To'] = email
        msg.attach(MIMEText(html_content, 'html'))

        with smtplib.SMTP(settings.SMTP_SERVER, settings.SMTP_PORT) as server:
            server.starttls()
            server.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
            server.send_message(msg)

        logger.info(f"Password reset email sent successfully to {email}")
        return True

    except smtplib.SMTPAuthenticationError as e:
        logger.error(f"SMTP authentication failed: {e}")
        if retry_count < max_retries:
            logger.info(f"Retrying... (attempt {retry_count + 1}/{max_retries})")
            return send_password_reset_email(email, temporary_password, nom, prenom, retry_count + 1)
        return False

    except smtplib.SMTPException as e:
        logger.error(f"SMTP error sending password reset email to {email}: {e}")
        if retry_count < max_retries:
            logger.info(f"Retrying... (attempt {retry_count + 1}/{max_retries})")
            return send_password_reset_email(email, temporary_password, nom, prenom, retry_count + 1)
        return False

    except Exception as e:
        logger.error(f"Unexpected error sending password reset email to {email}: {e}")
        if retry_count < max_retries:
            logger.info(f"Retrying... (attempt {retry_count + 1}/{max_retries})")
            return send_password_reset_email(email, temporary_password, nom, prenom, retry_count + 1)
        return False
        
    except smtplib.SMTPException as e:
        logger.error(f"SMTP error sending email to {email}: {e}")
        if retry_count < max_retries:
            logger.info(f"Retrying... (attempt {retry_count + 1}/{max_retries})")
            return send_welcome_email(email, temporary_password, nom, prenom, retry_count + 1)
        return False
        
    except Exception as e:
        logger.error(f"Unexpected error sending email to {email}: {e}")
        if retry_count < max_retries:
            logger.info(f"Retrying... (attempt {retry_count + 1}/{max_retries})")
            return send_welcome_email(email, temporary_password, nom, prenom, retry_count + 1)
        return False
